version: '3.7'

volumes:
  theshop_postgres_data:
      driver: local

services:
  nginx:
    image: nginx:1.19
    container_name: theshop_nginx
    ports: 
    - '80:80'
    volumes: 
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/proxy_params:/etc/nginx/proxy_params
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: theshop_keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: identity
      DB_USER: identity
      DB_SCHEMA: public
      DB_PASSWORD: identity
      KEYCLOAK_USER: julius
      KEYCLOAK_PASSWORD: julius123
    ports:
    - 8080:8080
    depends_on:
    - postgres

  postgres:
    image: postgres:13
    container_name: theshop_postgres
    volumes:
    - theshop_postgres_data:/var/lib/postgresql/data
    - ./postgres/initialize-db.sh:/docker-entrypoint-initdb.d/initialize-db.sh
    environment:
      POSTGRES_USER: julius
      POSTGRES_PASSWORD: julius123
      POSTGRES_MULTIPLE_DATABASES: identity,master,resk,aparel,dulcet
    ports:
    - 5432:5432