spring:
  r2dbc:
    url: r2dbc:postgresql://postgres/master
    password: master
    username: master
    properties:
      schema: catalogs
      statement_timeout: 10
  security:
    oauth2:
      client:
        provider:
          shop:
            issuer-uri: http://localhost:8080/auth/realms/tenant
            user-name-attribute: preferred_username
        registration:
          shop:
            client-id: shop_service
            client-secret: 1765b0be-cf9b-4049-8913-88050d466673
server:
  port: 8082
  forward-headers-strategy: framework

shop:
  domain-pattern: '([a-zA-Z0-9]*).${shop.base-domain}'
  domain-template: '{tenant}.${shop.base-domain}'
  base-domain: theshop.com
  database-host: localhost

logging:
  level:
    com.juliuskrah.shop: debug