spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/master
    password: master
    username: master
  security:
    oauth2:
      client:
        provider:
          shop:
            issuer-uri: http://localhost:8080/auth/realms/tenant
            user-name-attribute: preferred_username
        registration:
          shop:
            client-id: shop_service
            client-secret: 19cbe823-5579-4f12-9319-2dc24e718d2a
server:
  port: 8082
  forward-headers-strategy: framework

shop:
  domain-pattern: '([a-zA-Z0-9]*).${shop.base-domain}'
  domain-template: '{tenant}.${shop.base-domain}'
  base-domain: theshop.com
  
logging:
  level:
    com.juliuskrah.shop: debug