version: '3'
services:
  mvp:
    # Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
        VARIANT: 15
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "false"
        INSTALL_NODE: "true"
        MAVEN_VERSION: "3.6.3"
        NODE_VERSION: "lts/*"
    init: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock 
      - m2:/root/.m2
      - .:/workspaces/mvp:cached
    network_mode: service:postgres
    # entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 

volumes:
  m2:
